name: Run tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php: [7.4, 8.0]
                laravel: [7.*, 8.*]
                dependency-version: [prefer-stable]
                include:
                    -   laravel: '7.0'
                        testbench: '5.0'
                    -   laravel: 8.*
                        testbench: 6.*
                    -   laravel: '8.0'
                        php: '8.0'
                        stability: highest
                        coverage: true
                stability:
                    -   lowest
                    -   highest
                exclude:
                    -   laravel: '7.0'
                        php: '8.0'
                    -   laravel: '8.0'
                        php: '8.0'
                        stability: lowest

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }} - (${{ matrix.stability }})

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: zip
                    coverage: none

            -   name: Configure Laravel and Laravel Testbench
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

            -   name: Install Composer Dependencies
                uses: ramsey/composer-install@v1
                with:
                    dependency-versions: ${{ matrix.stability }}
                    composer-options: "--ignore-platform-req=php"

            -   name: Execute tests
                id: phpunit
                run:
                    vendor/bin/phpunit --coverage-clover=coverage.clover
